name: "Install"
description: "Set up NodeJS and runs install"

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8
        
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Setup git user
      shell: bash
      run: |
        git config --global user.email "wurmlitv@gmail.com"
        git config --global user.name "David Stüwe"

    - name: Install dependencies
      shell: bash
      run: pnpm install